"use client"

import { createContext, useContext, useState, type ReactNode } from "react"

type Language = "en" | "zh"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations = {
  en: {
    // Navigation
    "nav.dashboard": "Dashboard",
    "nav.users": "User Management",
    "nav.permissions": "Permission Management",
    "nav.leads": "Lead Management",
    "nav.assets": "Asset Management",
    "nav.orders": "Order Management",
    "nav.products": "Product Management",
    "nav.transactions": "Transactions",
    "nav.risk": "Risk Management",
    "nav.compliance": "Compliance",
    "nav.reports": "Reports & Analytics",
    "nav.monitoring": "System Monitoring",
    "nav.ai": "AI Assistant",
    "nav.baozugong": "Landlord · Options",
    "nav.settings": "Settings",

    // Auth
    "auth.login": "Login",
    "auth.register": "Register",
    "auth.logout": "Logout",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.confirmPassword": "Confirm Password",
    "auth.firstName": "First Name",
    "auth.lastName": "Last Name",
    "auth.company": "Company",
    "auth.rememberMe": "Remember me",
    "auth.forgotPassword": "Forgot password?",
    "auth.noAccount": "Don't have an account?",
    "auth.hasAccount": "Already have an account?",
    "auth.signIn": "Sign In",
    "auth.signUp": "Sign Up",
    "auth.createAccount": "Create Account",
    "auth.welcomeBack": "Welcome back",
    "auth.getStarted": "Get started with your account",
    "auth.invalidCredentials": "Invalid email or password",
    "auth.registrationFailed": "Registration failed. Please try again.",
    "auth.passwordMismatch": "Passwords do not match",
    "auth.passwordTooShort": "Password must be at least 6 characters",
    "auth.demoCredentials": "Demo credentials: admin@fincrm.com / admin123",

    // AI Assistant
    "ai.title": "AI Assistant",
    "ai.description": "Intelligent financial analysis and recommendations",
    "ai.chat": "AI Chat",
    "ai.analysis": "Smart Analysis",
    "ai.recommendations": "AI Recommendations",
    "ai.insights": "Market Insights",
    "ai.riskAnalysis": "Risk Analysis",
    "ai.portfolioOptimization": "Portfolio Optimization",
    "ai.marketPrediction": "Market Prediction",
    "ai.complianceCheck": "Compliance Check",
    "ai.customerInsights": "Customer Insights",
    "ai.fraudDetection": "Fraud Detection",
    "ai.chatPlaceholder": "Ask me anything about your financial data...",
    "ai.send": "Send",
    "ai.clear": "Clear Chat",
    "ai.analyzing": "Analyzing...",
    "ai.generateReport": "Generate AI Report",
    "ai.smartAlerts": "Smart Alerts",
    "ai.predictiveAnalytics": "Predictive Analytics",
    "ai.knowledgeBase": "Knowledge Base",
    "ai.quickAnalysis": "Quick Analysis",
    "ai.askQuestion": "Ask a question...",
    "ai.minimize": "Minimize",
    "ai.maximize": "Maximize",
    "ai.close": "Close",
    "ai.typing": "AI is typing...",
    "ai.error": "Sorry, I encountered an error. Please try again.",
    "ai.welcome": "Hello! I'm your AI financial assistant. How can I help you today?",

    // AI Features
    "ai.features.customerAnalysis": "Customer Analysis",
    "ai.features.customerAnalysisDesc": "AI-powered customer behavior analysis and segmentation",
    "ai.features.riskAssessment": "Risk Assessment",
    "ai.features.riskAssessmentDesc": "Intelligent risk evaluation and early warning system",
    "ai.features.investmentAdvice": "Investment Advice",
    "ai.features.investmentAdviceDesc": "Personalized investment recommendations based on AI analysis",
    "ai.features.marketForecast": "Market Forecast",
    "ai.features.marketForecastDesc": "AI-driven market trend prediction and analysis",
    "ai.features.complianceMonitoring": "Compliance Monitoring",
    "ai.features.complianceMonitoringDesc": "Automated compliance checking and regulatory monitoring",
    "ai.features.fraudPrevention": "Fraud Prevention",
    "ai.features.fraudPreventionDesc": "Real-time fraud detection and prevention system",

    // Dashboard
    "dashboard.title": "Financial CRM Dashboard",
    "dashboard.totalRevenue": "Total Revenue",
    "dashboard.activeClients": "Active Clients",
    "dashboard.newLeads": "New Leads",
    "dashboard.conversionRate": "Conversion Rate",
    "dashboard.recentTransactions": "Recent Transactions",
    "dashboard.topPerformers": "Top Performers",
    "dashboard.riskAlerts": "Risk Alerts",
    "dashboard.complianceStatus": "Compliance Status",
    "dashboard.overview": "Overview",
    "dashboard.performance": "Performance",
    "dashboard.analytics": "Analytics",

    // Users
    "users.title": "User Management",
    "users.description": "Manage system users and their access",
    "users.addUser": "Add User",
    "users.editUser": "Edit User",
    "users.deleteUser": "Delete User",
    "users.userDetails": "User Details",
    "users.role": "Role",
    "users.lastLogin": "Last Login",
    "users.createdAt": "Created At",

    // Permissions
    "permissions.title": "Permission Management",
    "permissions.description": "Manage user roles and permissions",
    "permissions.roles": "Roles",
    "permissions.permissions": "Permissions",
    "permissions.addRole": "Add Role",
    "permissions.editRole": "Edit Role",
    "permissions.deleteRole": "Delete Role",
    "permissions.assignPermissions": "Assign Permissions",
    "permissions.roleName": "Role Name",
    "permissions.roleDescription": "Role Description",

    // Leads
    "leads.title": "Lead Management",
    "leads.description": "Manage potential clients and opportunities",
    "leads.addLead": "Add Lead",
    "leads.editLead": "Edit Lead",
    "leads.deleteLead": "Delete Lead",
    "leads.leadSource": "Lead Source",
    "leads.leadStatus": "Lead Status",
    "leads.assignedTo": "Assigned To",
    "leads.followUp": "Follow Up",
    "leads.convert": "Convert to Client",

    // Assets
    "assets.title": "Asset Management",
    "assets.description": "Manage client assets and portfolios",
    "assets.totalValue": "Total Asset Value",
    "assets.portfolios": "Portfolios",
    "assets.performance": "Performance",
    "assets.allocation": "Asset Allocation",
    "assets.addAsset": "Add Asset",
    "assets.assetType": "Asset Type",
    "assets.currentValue": "Current Value",
    "assets.purchasePrice": "Purchase Price",
    "assets.returnRate": "Return Rate",

    // Products
    "products.title": "Product Management",
    "products.description": "Manage financial products and services",
    "products.totalProducts": "Total Products",
    "products.activeProducts": "Active Products",
    "products.categories": "Categories",
    "products.addProduct": "Add Product",
    "products.productName": "Product Name",
    "products.productType": "Product Type",
    "products.price": "Price",
    "products.availability": "Availability",

    // Transactions
    "transactions.title": "Transaction Management",
    "transactions.description": "View and manage all transactions",
    "transactions.totalTransactions": "Total Transactions",
    "transactions.totalVolume": "Total Volume",
    "transactions.todayTransactions": "Today's Transactions",
    "transactions.pendingTransactions": "Pending Transactions",
    "transactions.transactionId": "Transaction ID",
    "transactions.transactionType": "Transaction Type",
    "transactions.client": "Client",

    // Risk Management
    "risk.title": "Risk Management",
    "risk.description": "Monitor and manage financial risks",
    "risk.riskScore": "Risk Score",
    "risk.highRiskClients": "High Risk Clients",
    "risk.riskAlerts": "Risk Alerts",
    "risk.portfolioRisk": "Portfolio Risk",
    "risk.riskLevel": "Risk Level",
    "risk.mitigation": "Mitigation",

    // Compliance
    "compliance.title": "Compliance Management",
    "compliance.description": "Ensure regulatory compliance",
    "compliance.kycStatus": "KYC Status",
    "compliance.amlScreening": "AML Screening",
    "compliance.complianceScore": "Compliance Score",
    "compliance.pendingReviews": "Pending Reviews",
    "compliance.lastReview": "Last Review",
    "compliance.nextReview": "Next Review",

    // Reports
    "reports.title": "Reports & Analytics",
    "reports.description": "Generate and view business reports",
    "reports.salesReport": "Sales Report",
    "reports.performanceReport": "Performance Report",
    "reports.riskReport": "Risk Report",
    "reports.complianceReport": "Compliance Report",
    "reports.generateReport": "Generate Report",
    "reports.downloadReport": "Download Report",

    // Monitoring
    "monitoring.title": "System Monitoring",
    "monitoring.description": "Monitor system performance and health",
    "monitoring.systemHealth": "System Health",
    "monitoring.activeUsers": "Active Users",
    "monitoring.serverStatus": "Server Status",
    "monitoring.databaseStatus": "Database Status",
    "monitoring.uptime": "Uptime",
    "monitoring.responseTime": "Response Time",

    // Settings
    "settings.title": "Settings",
    "settings.description": "Configure system settings",
    "settings.general": "General",
    "settings.security": "Security",
    "settings.notifications": "Notifications",
    "settings.integrations": "Integrations",
    "settings.backup": "Backup",

    // Common
    "common.search": "Search...",
    "common.add": "Add",
    "common.edit": "Edit",
    "common.delete": "Delete",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.actions": "Actions",
    "common.status": "Status",
    "common.date": "Date",
    "common.amount": "Amount",
    "common.name": "Name",
    "common.email": "Email",
    "common.phone": "Phone",
    "common.address": "Address",
    "common.active": "Active",
    "common.inactive": "Inactive",
    "common.pending": "Pending",
    "common.approved": "Approved",
    "common.rejected": "Rejected",
    "common.view": "View",
    "common.export": "Export",
    "common.import": "Import",
    "common.filter": "Filter",
    "common.sort": "Sort",
    "common.refresh": "Refresh",
    "common.loading": "Loading...",
    "common.noData": "No data available",
    "common.total": "Total",
    "common.average": "Average",
    "common.high": "High",
    "common.medium": "Medium",
    "common.low": "Low",
    "common.yes": "Yes",
    "common.no": "No",
    "common.confirm": "Confirm",
    "common.close": "Close",
    "common.success": "Success",
    "common.error": "Error",
    "common.warning": "Warning",
    "common.info": "Info",
    "common.details": "Details",
    "common.description": "Description",
    "common.category": "Category",
    "common.type": "Type",
    "common.value": "Value",
    "common.created": "Created",
    "common.updated": "Updated",
    "common.by": "By",
    "common.at": "At",
    "common.from": "From",
    "common.to": "To",
    "common.all": "All",
    "common.none": "None",
    "common.select": "Select",
    "common.clear": "Clear",
    "common.reset": "Reset",
    "common.apply": "Apply",
    "common.submit": "Submit",
    "common.next": "Next",
    "common.previous": "Previous",
    "common.first": "First",
    "common.last": "Last",
    "common.page": "Page",
    "common.of": "of",
    "common.items": "items",
    "common.showing": "Showing",
    "common.results": "results",

    // Notifications
    "notifications.title": "Notifications",
    "notifications.newLead": "New lead assigned",
    "notifications.riskAlert": "Risk alert",
    "notifications.complianceReview": "Compliance review",
    "notifications.markAsRead": "Mark as read",
    "notifications.markAllAsRead": "Mark all as read",
    "notifications.viewAll": "View all",

    // Profile
    "profile.title": "Profile",
    "profile.personalInfo": "Personal Information",
    "profile.changePassword": "Change Password",
    "profile.preferences": "Preferences",
    "profile.avatar": "Avatar",
    "profile.updateProfile": "Update Profile",
  },
  zh: {
    // Navigation
    "nav.dashboard": "数据大盘",
    "nav.users": "用户管理",
    "nav.permissions": "权限管理",
    "nav.leads": "客户线索",
    "nav.assets": "资产管理",
    "nav.orders": "订单管理",
    "nav.products": "产品管理",
    "nav.transactions": "交易记录",
    "nav.risk": "风险管理",
    "nav.compliance": "合规管理",
    "nav.reports": "报表分析",
    "nav.monitoring": "数据监控",
    "nav.ai": "AI助手",
    "nav.baozugong": "包租公·期权",
    "nav.settings": "系统配置",

    // Auth
    "auth.login": "登录",
    "auth.register": "注册",
    "auth.logout": "退出登录",
    "auth.email": "邮箱",
    "auth.password": "密码",
    "auth.confirmPassword": "确认密码",
    "auth.firstName": "名",
    "auth.lastName": "姓",
    "auth.company": "公司",
    "auth.rememberMe": "记住我",
    "auth.forgotPassword": "忘记密码？",
    "auth.noAccount": "还没有账户？",
    "auth.hasAccount": "已有账户？",
    "auth.signIn": "登录",
    "auth.signUp": "注册",
    "auth.createAccount": "创建账户",
    "auth.welcomeBack": "欢迎回来",
    "auth.getStarted": "开始使用您的账户",
    "auth.invalidCredentials": "邮箱或密码错误",
    "auth.registrationFailed": "注册失败，请重试",
    "auth.passwordMismatch": "密码不匹配",
    "auth.passwordTooShort": "密码至少需要6个字符",
    "auth.demoCredentials": "演示账户：admin@fincrm.com / admin123",

    // AI Assistant
    "ai.title": "AI智能助手",
    "ai.description": "智能金融分析和建议",
    "ai.chat": "AI对话",
    "ai.analysis": "智能分析",
    "ai.recommendations": "AI建议",
    "ai.insights": "市场洞察",
    "ai.riskAnalysis": "风险分析",
    "ai.portfolioOptimization": "投资组合优化",
    "ai.marketPrediction": "市场预测",
    "ai.complianceCheck": "合规检查",
    "ai.customerInsights": "客户洞察",
    "ai.fraudDetection": "欺诈检测",
    "ai.chatPlaceholder": "询问任何关于您财务数据的问题...",
    "ai.send": "发送",
    "ai.clear": "清空对话",
    "ai.analyzing": "分析中...",
    "ai.generateReport": "生成AI报告",
    "ai.smartAlerts": "智能预警",
    "ai.predictiveAnalytics": "预测分析",
    "ai.knowledgeBase": "知识库",
    "ai.quickAnalysis": "快速分析",
    "ai.askQuestion": "提出问题...",
    "ai.minimize": "最小化",
    "ai.maximize": "最大化",
    "ai.close": "关闭",
    "ai.typing": "AI正在输入...",
    "ai.error": "抱歉，遇到了错误，请重试",
    "ai.welcome": "您好！我是您的AI金融助手，今天我能为您做些什么？",

    // AI Features
    "ai.features.customerAnalysis": "客户分析",
    "ai.features.customerAnalysisDesc": "AI驱动的客户行为分析和细分",
    "ai.features.riskAssessment": "风险评估",
    "ai.features.riskAssessmentDesc": "智能风险评估和预警系统",
    "ai.features.investmentAdvice": "投资建议",
    "ai.features.investmentAdviceDesc": "基于AI分析的个性化投资建议",
    "ai.features.marketForecast": "市场预测",
    "ai.features.marketForecastDesc": "AI驱动的市场趋势预测和分析",
    "ai.features.complianceMonitoring": "合规监控",
    "ai.features.complianceMonitoringDesc": "自动化合规检查和监管监控",
    "ai.features.fraudPrevention": "欺诈防范",
    "ai.features.fraudPreventionDesc": "实时欺诈检测和防范系统",

    // Dashboard
    "dashboard.title": "金融CRM管理系统",
    "dashboard.totalRevenue": "总收入",
    "dashboard.activeClients": "活跃客户",
    "dashboard.newLeads": "新增线索",
    "dashboard.conversionRate": "转化率",
    "dashboard.recentTransactions": "最近交易",
    "dashboard.topPerformers": "业绩排行",
    "dashboard.riskAlerts": "风险预警",
    "dashboard.complianceStatus": "合规状态",
    "dashboard.overview": "概览",
    "dashboard.performance": "业绩",
    "dashboard.analytics": "分析",

    // Users
    "users.title": "用户管理",
    "users.description": "管理系统用户及其访问权限",
    "users.addUser": "添加用户",
    "users.editUser": "编辑用户",
    "users.deleteUser": "删除用户",
    "users.userDetails": "用户详情",
    "users.role": "角色",
    "users.lastLogin": "最后登录",
    "users.createdAt": "创建时间",

    // Permissions
    "permissions.title": "权限管理",
    "permissions.description": "管理用户角色和权限",
    "permissions.roles": "角色",
    "permissions.permissions": "权限",
    "permissions.addRole": "添加角色",
    "permissions.editRole": "编辑角色",
    "permissions.deleteRole": "删除角色",
    "permissions.assignPermissions": "分配权限",
    "permissions.roleName": "角色名称",
    "permissions.roleDescription": "角色描述",

    // Leads
    "leads.title": "客户线索管理",
    "leads.description": "管理潜在客户和商机",
    "leads.addLead": "添加线索",
    "leads.editLead": "编辑线索",
    "leads.deleteLead": "删除线索",
    "leads.leadSource": "线索来源",
    "leads.leadStatus": "线索状态",
    "leads.assignedTo": "分配给",
    "leads.followUp": "跟进",
    "leads.convert": "转为客户",

    // Assets
    "assets.title": "资产管理",
    "assets.description": "管理客户资产和投资组合",
    "assets.totalValue": "资产总值",
    "assets.portfolios": "投资组合",
    "assets.performance": "业绩表现",
    "assets.allocation": "资产配置",
    "assets.addAsset": "添加资产",
    "assets.assetType": "资产类型",
    "assets.currentValue": "当前价值",
    "assets.purchasePrice": "购买价格",
    "assets.returnRate": "收益率",

    // Products
    "products.title": "产品管理",
    "products.description": "管理金融产品和服务",
    "products.totalProducts": "产品总数",
    "products.activeProducts": "活跃产品",
    "products.categories": "产品类别",
    "products.addProduct": "添加产品",
    "products.productName": "产品名称",
    "products.productType": "产品类型",
    "products.price": "价格",
    "products.availability": "可用性",

    // Transactions
    "transactions.title": "交易管理",
    "transactions.description": "查看和管理所有交易",
    "transactions.totalTransactions": "交易总数",
    "transactions.totalVolume": "交易总额",
    "transactions.todayTransactions": "今日交易",
    "transactions.pendingTransactions": "待处理交易",
    "transactions.transactionId": "交易ID",
    "transactions.transactionType": "交易类型",
    "transactions.client": "客户",

    // Risk Management
    "risk.title": "风险管理",
    "risk.description": "监控和管理金融风险",
    "risk.riskScore": "风险评分",
    "risk.highRiskClients": "高风险客户",
    "risk.riskAlerts": "风险预警",
    "risk.portfolioRisk": "组合风险",
    "risk.riskLevel": "风险等级",
    "risk.mitigation": "风险缓解",

    // Compliance
    "compliance.title": "合规管理",
    "compliance.description": "确保监管合规",
    "compliance.kycStatus": "KYC状态",
    "compliance.amlScreening": "反洗钱筛查",
    "compliance.complianceScore": "合规评分",
    "compliance.pendingReviews": "待审核项目",
    "compliance.lastReview": "最后审核",
    "compliance.nextReview": "下次审核",

    // Reports
    "reports.title": "报表分析",
    "reports.description": "生成和查看业务报表",
    "reports.salesReport": "销售报表",
    "reports.performanceReport": "业绩报表",
    "reports.riskReport": "风险报表",
    "reports.complianceReport": "合规报表",
    "reports.generateReport": "生成报表",
    "reports.downloadReport": "下载报表",

    // Monitoring
    "monitoring.title": "系统监控",
    "monitoring.description": "监控系统性能和健康状态",
    "monitoring.systemHealth": "系统健康",
    "monitoring.activeUsers": "活跃用户",
    "monitoring.serverStatus": "服务器状态",
    "monitoring.databaseStatus": "数据库状态",
    "monitoring.uptime": "运行时间",
    "monitoring.responseTime": "响应时间",

    // Settings
    "settings.title": "系统设置",
    "settings.description": "配置系统设置",
    "settings.general": "常规",
    "settings.security": "安全",
    "settings.notifications": "通知",
    "settings.integrations": "集成",
    "settings.backup": "备份",

    // Common
    "common.search": "搜索...",
    "common.add": "添加",
    "common.edit": "编辑",
    "common.delete": "删除",
    "common.save": "保存",
    "common.cancel": "取消",
    "common.actions": "操作",
    "common.status": "状态",
    "common.date": "日期",
    "common.amount": "金额",
    "common.name": "姓名",
    "common.email": "邮箱",
    "common.phone": "电话",
    "common.address": "地址",
    "common.active": "活跃",
    "common.inactive": "非活跃",
    "common.pending": "待处理",
    "common.approved": "已批准",
    "common.rejected": "已拒绝",
    "common.view": "查看",
    "common.export": "导出",
    "common.import": "导入",
    "common.filter": "筛选",
    "common.sort": "排序",
    "common.refresh": "刷新",
    "common.loading": "加载中...",
    "common.noData": "暂无数据",
    "common.total": "总计",
    "common.average": "平均",
    "common.high": "高",
    "common.medium": "中",
    "common.low": "低",
    "common.yes": "是",
    "common.no": "否",
    "common.confirm": "确认",
    "common.close": "关闭",
    "common.success": "成功",
    "common.error": "错误",
    "common.warning": "警告",
    "common.info": "信息",
    "common.details": "详情",
    "common.description": "描述",
    "common.category": "类别",
    "common.type": "类型",
    "common.value": "值",
    "common.created": "创建",
    "common.updated": "更新",
    "common.by": "由",
    "common.at": "于",
    "common.from": "从",
    "common.to": "到",
    "common.all": "全部",
    "common.none": "无",
    "common.select": "选择",
    "common.clear": "清空",
    "common.reset": "重置",
    "common.apply": "应用",
    "common.submit": "提交",
    "common.next": "下一页",
    "common.previous": "上一页",
    "common.first": "首页",
    "common.last": "末页",
    "common.page": "页",
    "common.of": "共",
    "common.items": "项",
    "common.showing": "显示",
    "common.results": "结果",

    // Notifications
    "notifications.title": "通知",
    "notifications.newLead": "新线索分配",
    "notifications.riskAlert": "风险预警",
    "notifications.complianceReview": "合规审核",
    "notifications.markAsRead": "标记为已读",
    "notifications.markAllAsRead": "全部标记为已读",
    "notifications.viewAll": "查看全部",

    // Profile
    "profile.title": "个人资料",
    "profile.personalInfo": "个人信息",
    "profile.changePassword": "修改密码",
    "profile.preferences": "偏好设置",
    "profile.avatar": "头像",
    "profile.updateProfile": "更新资料",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en")

  const t = (key: string): string => {
    return translations[language][key as keyof (typeof translations)["en"]] || key
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
